In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("medical_insurance.csv")
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [8]:
df["sex"].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [14]:
df["sex"].replace({"male":1, "female":0},inplace=True)

In [16]:
df["smoker"].value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [17]:
df["smoker"].replace({"yes":1,"no":0},inplace=True)

In [18]:
df

age  sex     bmi  children  smoker     region      charges
0      19    0  27.900         0       1  southwest  16884.92400
1      18    1  33.770         1       0  southeast   1725.55230
2      28    1  33.000         3       0  southeast   4449.46200
3      33    1  22.705         0       0  northwest  21984.47061
4      32    1  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    1  30.970         3       0  northwest  10600.54830
1334   18    0  31.920         0       0  northeast   2205.98080
1335   18    0  36.850         0       0  southeast   1629.83350
1336   21    0  25.800         0       0  southwest   2007.94500
1337   61    0  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [19]:
df["region"].value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

In [20]:
df["region"].replace({"southeast":1, "southwest":2, "northwest":3, "northeast":4},inplace=True)

In [21]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       2  16884.92400
1      18    1  33.770         1       0       1   1725.55230
2      28    1  33.000         3       0       1   4449.46200
3      33    1  22.705         0       0       3  21984.47061
4      32    1  28.880         0       0       3   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       3  10600.54830
1334   18    0  31.920         0       0       4   2205.98080
1335   18    0  36.850         0       0       1   1629.83350
1336   21    0  25.800         0       0       2   2007.94500
1337   61    0  29.070         0       1       3  29141.36030

[1338 rows x 7 columns]

## train rest split

In [27]:
x = df.drop('charges', axis =1)
y = df["charges"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=34)

## model training


In [30]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [33]:
#testing data evaluation
y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
print("MSE is:", mse)

rmse = np.sqrt(mse)
print("rmse:", rmse)

mae = mean_absolute_error(y_test,y_pred)
print("mae is:", mae)

r2 = r2_score(y_test,y_pred)
print("R2 score:", r2)

MSE is: 39718633.636179104
rmse: 6302.272101090138
mae is: 4343.691907697813
R2 score: 0.7463970382096046


In [34]:
#training data evaluation
y_pred_train = model.predict(x_train)

mse = mean_squared_error(y_train, y_pred_train)
print("MSE is:", mse)

rmse = np.sqrt(mse)
print("rmse:", rmse)

mae = mean_absolute_error(y_train,y_pred_train)
print("mae is:", mae)

r2 = r2_score(y_train,y_pred_train)
print("R2 score:", r2)

MSE is: 35471286.47017714
rmse: 5955.777570576082
mae is: 4086.429928701325
R2 score: 0.7517174623019243


## testing a single row

In [35]:
x.head(1).T

0
age       19.0
sex        0.0
bmi       27.9
children   0.0
smoker     1.0
region     2.0

In [63]:
age= 30
sex= "female"
bmi= 27
children = 2
smoker = "no"
region = "southwest"

# charges =?

In [54]:
column_names = x.columns
column_names

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region'], dtype='object')

In [55]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0., 0., 0.])

In [64]:
label_encoded_data = { 'sex' : {"male":1,"female":0},
                      'smoker':{"yes":1,"no":0},
                
                      "region":{"southeast":1, "southwest":2, "northwest":3, "northeast":4}}

In [65]:
# label_encoded_data["smoker"][smoker]
# label_encoded_data["region"][region]
label_encoded_data["sex"][sex]

0

In [66]:
label_encoded_data

{'sex': {'male': 1, 'female': 0},
 'smoker': {'yes': 1, 'no': 0},
 'region': {'southeast': 1, 'southwest': 2, 'northwest': 3, 'northeast': 4}}

In [67]:
# now filling the dummy array

In [68]:
test_array[0] = age
test_array[1] =label_encoded_data["sex"][sex]
test_array[2] = bmi
test_array[3] = children
test_array[4] = label_encoded_data["smoker"][smoker]
test_array[5] = label_encoded_data["region"][region]

In [69]:
test_array

array([30.,  0., 27.,  2.,  0.,  2.])

In [70]:
model.predict([test_array])

C:\Users\SAVINAY\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5092.63504673])

In [71]:
# create model file
import pickle

with open("Linear_model.pkl","wb") as f:
    pickle.dump(model,f)

In [72]:
project_data =  { 'sex' : {"male":1,"female":0},
                      'smoker':{"yes":1,"no":0},
                "region":{"southeast":1, "southwest":2, "northwest":3, "northeast":4},
                "columns" : list(x.columns)}

In [73]:
import json

with  open("project_data.json","w") as f:
    json.dump(project_data,f)